In [16]:
import torch
from zmq.green import device

torch.__version__

'2.5.1'

In [17]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [18]:
x = torch.rand(4, 2)
print(x)

tensor([[0.7718, 0.9751],
        [0.6092, 0.9924],
        [0.6744, 0.2780],
        [0.4965, 0.8119]])


In [19]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [20]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [21]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [22]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.3540, -1.6643, -1.3765, -0.2849],
        [ 1.4816, -0.7689, -0.1774, -1.5032]])


In [23]:
print(x.size())

torch.Size([2, 4])


In [24]:
x = torch.rand(1)
print(x.item())

0.5643720030784607


In [26]:
device = torch.device('cpu')
y = torch.ones_like(x, device=device)
x = x.to(device)

In [27]:
print(x)
print(y)

z = x + y
print(z)
z.to('cpu', dtype=torch.double)

tensor([0.5644])
tensor([1.])
tensor([1.5644])


tensor([1.5644], dtype=torch.float64)

In [28]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [29]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [30]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

4D Tensor
- 컬러이미지 데이터가 대표적인 사례
- sample, height, width, channel

5D Tensor
- sample, frame, width, height, channel

In [37]:
import math

a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil_(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[ 0.6094, -0.7659]])
tensor([[0.6094, 0.7659]])
tensor([[1., -0.]])
tensor([[1., -0.]])
tensor([[0.5000, -0.0000]])


In [38]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(a))

tensor([[1., -0.]])
tensor(-0.)
tensor(1.)
tensor(0.5000)
tensor(0.7071)
tensor(-0.)
tensor([-0., 1.])


In [42]:
x = torch.randn(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))
print(torch.argmax(x, dim=0))

tensor([[ 2.0503, -0.7806],
        [-2.6636, -1.9560]])
torch.return_types.max(
values=tensor([ 2.0503, -0.7806]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([ 2.0503, -1.9560]),
indices=tensor([0, 1]))
tensor([0, 0])


In [43]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)

In [44]:
print(torch.add(x, y))
print(x + y)

tensor([[-1.7302, -1.2362],
        [-1.4783,  1.2158]])
tensor([[-1.7302, -1.2362],
        [-1.4783,  1.2158]])


In [52]:
z = torch.tensor([
    [1,2],
    [3,4]
])
y = torch.tensor([
    [1,2],
    [3,4]]
)
print(torch.matmul(z, y))
print(z@y)


tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [54]:
print(z[:, 0])
print(z[:, 1])
print(z[0, :])
print(z[1, :])

tensor([1, 3])
tensor([2, 4])
tensor([1, 2])
tensor([3, 4])


In [56]:
x = torch.randn(4, 5)
print(x)
y = x.view(20) # flatten
print(y)
z = x.view(5, -1)
print(z)

tensor([[ 1.0712,  0.7506, -0.4227,  0.1923, -0.9132],
        [-0.4535, -2.1552, -0.8627,  0.3467,  1.0271],
        [-2.0302, -0.9511,  0.4472, -0.2679, -0.7709],
        [ 0.2342,  0.0965,  0.7605, -1.4916, -1.5051]])
tensor([ 1.0712,  0.7506, -0.4227,  0.1923, -0.9132, -0.4535, -2.1552, -0.8627,
         0.3467,  1.0271, -2.0302, -0.9511,  0.4472, -0.2679, -0.7709,  0.2342,
         0.0965,  0.7605, -1.4916, -1.5051])
tensor([[ 1.0712,  0.7506, -0.4227,  0.1923],
        [-0.9132, -0.4535, -2.1552, -0.8627],
        [ 0.3467,  1.0271, -2.0302, -0.9511],
        [ 0.4472, -0.2679, -0.7709,  0.2342],
        [ 0.0965,  0.7605, -1.4916, -1.5051]])


In [58]:
tensor = torch.randn(1, 3, 3)
print(tensor)
print(tensor.shape)
print(tensor.ndim)

tensor([[[ 0.3605,  0.0807, -0.0204],
         [ 2.0081, -0.5557, -0.3361],
         [ 1.4791, -0.9060,  1.1515]]])
torch.Size([1, 3, 3])
3


In [59]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[ 0.3605,  0.0807, -0.0204],
        [ 2.0081, -0.5557, -0.3361],
        [ 1.4791, -0.9060,  1.1515]])
torch.Size([3, 3])


In [62]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[0.7338, 0.4475, 0.9613],
        [0.0238, 0.8801, 0.7849],
        [0.9172, 0.1300, 0.2191]])
torch.Size([3, 3])
tensor([[[0.7338, 0.4475, 0.9613]],

        [[0.0238, 0.8801, 0.7849]],

        [[0.9172, 0.1300, 0.2191]]])
torch.Size([3, 1, 3])


In [63]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.7338],
         [0.4475],
         [0.9613]],

        [[0.0238],
         [0.8801],
         [0.7849]],

        [[0.9172],
         [0.1300],
         [0.2191]]])
torch.Size([3, 3, 1])


In [69]:
x = torch.FloatTensor([1, 4])
print(x)
y = torch.LongTensor([2, 5])
print(y)
z = torch.LongTensor([3, 6])
print(z)

stacked = torch.stack([x, y, z], dim=0)
print(stacked)
print(stacked.shape)
print(stacked.ndim)

tensor([1., 4.])
tensor([2, 5])
tensor([3, 6])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])
2


In [70]:
stacked = torch.stack([x, y, z], dim=1)
print(stacked)
print(stacked.shape)
print(stacked.ndim)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
2


In [76]:
tensor = torch.rand(3, 6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, chunks=3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.7247, 0.6910, 0.8462, 0.9675, 0.7412, 0.8887],
        [0.6050, 0.8672, 0.5572, 0.0657, 0.0583, 0.1714],
        [0.6684, 0.7386, 0.8101, 0.6004, 0.9570, 0.7398]])
tensor([[0.7247, 0.6910],
        [0.6050, 0.8672],
        [0.6684, 0.7386]])
tensor([[0.8462, 0.9675],
        [0.5572, 0.0657],
        [0.8101, 0.6004]])
tensor([[0.7412, 0.8887],
        [0.0583, 0.1714],
        [0.9570, 0.7398]])


In [77]:
t1, t2, t3 = torch.chunk(tensor, chunks=3, dim=0)
print(t1)
print(t2)
print(t3)

tensor([[0.7247, 0.6910, 0.8462, 0.9675, 0.7412, 0.8887]])
tensor([[0.6050, 0.8672, 0.5572, 0.0657, 0.0583, 0.1714]])
tensor([[0.6684, 0.7386, 0.8101, 0.6004, 0.9570, 0.7398]])


In [78]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [79]:
a = torch.randn(3, 3)
a = a * 3
print(a)
print(a.requires_grad)

tensor([[-2.8003, -1.2171, -1.8291],
        [ 1.9693,  4.1313, -3.6246],
        [-5.2911,  5.9540, -7.4197]])
False


In [80]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [83]:
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor(165.2494, grad_fn=<SumBackward0>)
