In [29]:
import torch

torch.__version__

'2.0.1+cu117'

In [30]:
x = torch.empty(4, 2)
print(x)

tensor([[4.6304e+27, 7.0060e+22],
        [1.0647e+24, 1.5766e-19],
        [4.7615e+30, 7.1428e+31],
        [1.1722e-19, 1.3563e-19]])


In [31]:
x = torch.rand(4, 2)
print(x)

tensor([[0.1216, 0.5541],
        [0.0387, 0.3151],
        [0.1011, 0.1397],
        [0.2936, 0.2210]])


In [32]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [33]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [34]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [35]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.0253, -0.4864,  0.3695, -0.3214],
        [-1.4707, -1.8049, -0.4769,  0.9904]])


In [36]:
print(x.size())

torch.Size([2, 4])


In [37]:
x = torch.rand(1)
print(x.item())

0.8868333101272583


In [38]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
y = torch.ones_like(x, device=device)
x = x.to(device)
print(device)

cuda


In [39]:
print(x)
print(y)

z = x + y
print(z)
z.to('cpu', dtype=torch.double)

tensor([0.8868], device='cuda:0')
tensor([1.], device='cuda:0')
tensor([1.8868], device='cuda:0')


tensor([1.8868], dtype=torch.float64)

In [40]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [41]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [42]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [43]:
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


4D Tensor
- 컬러이미지 데이터가 대표적인 사례
- sample, height, width, channel

5D Tensor
- sample, frame, width, height, channel

In [44]:
import math

a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil_(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.0367,  0.4985]])
tensor([[0.0367, 0.4985]])
tensor([[-0., 1.]])
tensor([[-0., 1.]])
tensor([[-0.0000, 0.5000]])


In [45]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(a))

tensor([[-0., 1.]])
tensor(-0.)
tensor(1.)
tensor(0.5000)
tensor(0.7071)
tensor(-0.)
tensor([-0., 1.])


In [46]:
x = torch.randn(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))
print(torch.argmax(x, dim=0))

tensor([[ 0.9280, -0.5852],
        [ 1.3150,  0.2725]])
torch.return_types.max(
values=tensor([1.3150, 0.2725]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.9280, 1.3150]),
indices=tensor([0, 0]))
tensor([1, 1])


In [47]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)

In [48]:
print(torch.add(x, y))
print(x + y)

tensor([[-1.2550,  0.1054],
        [ 0.6988,  1.4256]])
tensor([[-1.2550,  0.1054],
        [ 0.6988,  1.4256]])


In [49]:
z = torch.tensor([
    [1,2],
    [3,4]
])
y = torch.tensor([
    [1,2],
    [3,4]]
)
print(torch.matmul(z, y))
print(z@y)


tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [50]:
print(z[:, 0])
print(z[:, 1])
print(z[0, :])
print(z[1, :])

tensor([1, 3])
tensor([2, 4])
tensor([1, 2])
tensor([3, 4])


In [51]:
x = torch.randn(4, 5)
print(x)
y = x.view(20) # flatten
print(y)
z = x.view(5, -1)
print(z)

tensor([[-1.4567, -0.3650,  1.0080, -2.7401, -1.3023],
        [-0.7538, -0.4551,  0.2776, -0.8538, -1.7445],
        [ 0.0840,  0.1661, -0.6834, -0.9611,  0.0672],
        [-1.5194,  0.0048, -1.4848, -0.9803, -1.5853]])
tensor([-1.4567, -0.3650,  1.0080, -2.7401, -1.3023, -0.7538, -0.4551,  0.2776,
        -0.8538, -1.7445,  0.0840,  0.1661, -0.6834, -0.9611,  0.0672, -1.5194,
         0.0048, -1.4848, -0.9803, -1.5853])
tensor([[-1.4567, -0.3650,  1.0080, -2.7401],
        [-1.3023, -0.7538, -0.4551,  0.2776],
        [-0.8538, -1.7445,  0.0840,  0.1661],
        [-0.6834, -0.9611,  0.0672, -1.5194],
        [ 0.0048, -1.4848, -0.9803, -1.5853]])


In [52]:
tensor = torch.randn(1, 3, 3)
print(tensor)
print(tensor.shape)
print(tensor.ndim)

tensor([[[ 2.0194,  0.0455, -0.0996],
         [ 0.2398,  0.4374,  0.2845],
         [-1.6796, -1.2840,  0.9352]]])
torch.Size([1, 3, 3])
3


In [53]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[ 2.0194,  0.0455, -0.0996],
        [ 0.2398,  0.4374,  0.2845],
        [-1.6796, -1.2840,  0.9352]])
torch.Size([3, 3])


In [54]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[0.0546, 0.4690, 0.1319],
        [0.8844, 0.3616, 0.3511],
        [0.3630, 0.8815, 0.7367]])
torch.Size([3, 3])
tensor([[[0.0546, 0.4690, 0.1319],
         [0.8844, 0.3616, 0.3511],
         [0.3630, 0.8815, 0.7367]]])
torch.Size([1, 3, 3])


In [55]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.0546],
         [0.4690],
         [0.1319]],

        [[0.8844],
         [0.3616],
         [0.3511]],

        [[0.3630],
         [0.8815],
         [0.7367]]])
torch.Size([3, 3, 1])


In [56]:
x = torch.FloatTensor([1, 4])
print(x)
y = torch.LongTensor([2, 5])
print(y)
z = torch.LongTensor([3, 6])
print(z)

stacked = torch.stack([x, y, z], dim=0)
print(stacked)
print(stacked.shape)
print(stacked.ndim)

tensor([1., 4.])
tensor([2, 5])
tensor([3, 6])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])
2


In [57]:
stacked = torch.stack([x, y, z], dim=1)
print(stacked)
print(stacked.shape)
print(stacked.ndim)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
2


In [58]:
tensor = torch.rand(3, 6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, chunks=3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.8020, 0.0220, 0.3365, 0.3837, 0.3087, 0.7031],
        [0.0376, 0.3953, 0.5414, 0.5894, 0.0559, 0.8894],
        [0.2571, 0.6950, 0.4598, 0.5621, 0.5508, 0.2570]])
tensor([[0.8020, 0.0220],
        [0.0376, 0.3953],
        [0.2571, 0.6950]])
tensor([[0.3365, 0.3837],
        [0.5414, 0.5894],
        [0.4598, 0.5621]])
tensor([[0.3087, 0.7031],
        [0.0559, 0.8894],
        [0.5508, 0.2570]])


In [59]:
t1, t2, t3 = torch.chunk(tensor, chunks=3, dim=0)
print(t1)
print(t2)
print(t3)

tensor([[0.8020, 0.0220, 0.3365, 0.3837, 0.3087, 0.7031]])
tensor([[0.0376, 0.3953, 0.5414, 0.5894, 0.0559, 0.8894]])
tensor([[0.2571, 0.6950, 0.4598, 0.5621, 0.5508, 0.2570]])


In [60]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [61]:
a = torch.randn(3, 3)
a = a * 3
print(a)
print(a.requires_grad)

tensor([[-2.1314, -2.3045,  2.6847],
        [-3.9056, -1.7610, -6.9829],
        [-0.5936,  1.3713, -1.2184]])
False


In [62]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [63]:
b = (a * a).sum()
print(b)
print(b.grad_fn)

tensor(87.8943, grad_fn=<SumBackward0>)


In [64]:
x = torch.ones(3, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [65]:
y = x + 5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [66]:
z = y * y
out = z.mean()
print(z, out)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [68]:
print(out)
print(out.backward())

tensor(36., grad_fn=<MeanBackward0>)


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [69]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [70]:
x = np.random.randn(10, 2)
print(x)

[[ 0.36560136 -0.8910513 ]
 [ 0.33887037 -0.45836467]
 [ 0.66258813 -0.84836346]
 [-0.25573364  0.87506508]
 [-0.61975925  0.92177587]
 [-0.79255545  0.82191339]
 [-0.89355721 -0.80998065]
 [-0.02675543 -0.02471064]
 [ 0.56413818 -0.70014696]
 [-0.15270576  0.668095  ]]
