In [16]:
import torch
from zmq.green import device

torch.__version__

'2.5.1'

In [17]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [18]:
x = torch.rand(4, 2)
print(x)

tensor([[0.7718, 0.9751],
        [0.6092, 0.9924],
        [0.6744, 0.2780],
        [0.4965, 0.8119]])


In [19]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [20]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [21]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [22]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.3540, -1.6643, -1.3765, -0.2849],
        [ 1.4816, -0.7689, -0.1774, -1.5032]])


In [23]:
print(x.size())

torch.Size([2, 4])


In [24]:
x = torch.rand(1)
print(x.item())

0.5643720030784607


In [26]:
device = torch.device('cpu')
y = torch.ones_like(x, device=device)
x = x.to(device)

In [27]:
print(x)
print(y)

z = x + y
print(z)
z.to('cpu', dtype=torch.double)

tensor([0.5644])
tensor([1.])
tensor([1.5644])


tensor([1.5644], dtype=torch.float64)

In [28]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [29]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [30]:
t2 = torch.tensor([[1,2,3], [4,5,6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
t3 = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

4D Tensor
- 컬러이미지 데이터가 대표적인 사례
- sample, height, width, channel

5D Tensor
- sample, frame, width, height, channel