In [1]:
import torch

torch.__version__

'2.5.1'

In [5]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [6]:
x = torch.rand(4, 2)
print(x)

tensor([[0.2977, 0.7202],
        [0.8380, 0.5313],
        [0.2744, 0.1910],
        [0.5458, 0.5265]])


In [8]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [9]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [11]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.3050,  0.3618,  0.5519, -1.9478],
        [-0.2771,  0.5817, -0.7308, -0.2336]])


In [14]:
print(x.size())

torch.Size([2, 4])
