In [2]:
import torch

a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = torch.tensor([1, 2, 3.1, 4])
print(b.dtype)
print(b)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [3]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 행렬의 수

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2
6


In [4]:
print(torch.zeros(3, 4))
print(torch.zeros_like(A))
print(torch.arange(1, 10, 3))
print(torch.linspace(0, 1, 10)) # linearspace 0~1 까지 10개 만들어줘

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([1, 4, 7])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [5]:
A = torch.tensor([[1, 2], [4, 5]])
B = torch.tensor([[1, 2], [4, 5]])
print(A*B) # hadammar product?
print(A@B) # np.dot

tensor([[ 1,  4],
        [16, 25]])
tensor([[ 9, 12],
        [24, 33]])
